application: wancp
version: 1
runtime: python
api_version: 1

handlers:
- url: /myremote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /tasks/prefresh
  script: index.py
  login: admin


- url: /css
  static_dir: css
- url: /images
  static_dir: images

- url: /testme
  script: test/test.py

- url: /zdbk_2043
  script: zipme.py

- url: /.*
  script: index.py

builtins:
- remote_api: on
